Repository RE-SS3D/SS3D, pull requests merged in 2021-06, with the labels that each got.

#670 Update documents
  .github/ISSUE_TEMPLATE/bug.md
  Documents/CONTRIBUTING.md
  Documents/Images/Twitter.png
  README.md
Labels: documentation, fix

#703 Fixes Disconnect button for clients
  Assets/Content/Systems/UI/Engine/ServerLobby/MainLobbyButtonHelper.cs
Labels: Fix

#704 Toggle flashlight and desk lamp bulb materials
  Assets/Content/Items/Functional/Tools/Generic/DeskLamp.cs
  Assets/Content/Items/Functional/Tools/Generic/Flashlight.cs
  Assets/Content/Items/Functional/Tools/Generic/desk lamp.prefab
  Assets/Content/Items/Functional/Tools/Generic/flashlight.prefab
Labels: Feature

#718 Updates Documents & GitHub
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Config.yml
  .github/ISSUE_TEMPLATE/Documentation.md
  .github/ISSUE_TEMPLATE/Feature.md
  .github/ISSUE_TEMPLATE/Suggestion.md
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/WORKFLOWS/Main.yml
  .github/pull_request_template.md
  Documents/CONTRIBUTING.md
  README.md
Labels: Needs: Review/Testing, Type: Documentation

#724 Document Details
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Config.yml
  .github/ISSUE_TEMPLATE/Feature.md
  Documents/CONTRIBUTING.md
Labels: Type: Documentation
