Repository RE-SS3D/SS3D, pull requests merged in 2021-07, with the labels that each got.

#729 Download Disclaimer
  README.md
Labels: Priority: 0 - Low, Type: Documentation

#738 Minor login system bugfixes
  Assets/Engine/Server/Mirror/SceneLoaderManager.cs
  Assets/Engine/Server/Round/RoundManager.cs
Labels: Type: Fix

#740 Add missing Examinables
  Assets/Content/Entities/Animals/Mammals/Corgi.prefab
  Assets/Content/Entities/Animals/Mammals/Corgi.prefab.meta
  Assets/Content/Items/Consumables/Food/General/Meat/EggSplatter1.prefab
  Assets/Content/Items/Consumables/Food/Meals/Sandwiches/Burger.prefab
  Assets/Content/Items/Cosmetic/Debri/AshPile.prefab
  Assets/Content/Items/Functional/Containers/Liquid/SpaceCleaner.prefab
  Assets/Content/Items/Functional/Tools/Construction/ScrewdriverBlue.prefab
Labels: Type: Fix

#739 Corrects issue where items are not on the Item layer.
  Assets/Content/Items/Clothing/Headwear/Helmets/HardHatRed.prefab
  Assets/Content/Items/Clothing/Headwear/Helmets/HardHatYellow.prefab
  Assets/Content/Items/Functional/Containers/Liquid/LargeBeaker.prefab
  Assets/Content/Items/Functional/Containers/Liquid/SmallBeaker.prefab
  Assets/Content/Items/Functional/Containers/Liquid/beaker.prefab
  Assets/Content/Items/Functional/Containers/Liquid/mug.prefab
  Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonBlack.prefab
  Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonBlue.prefab
  Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonGreen.prefab
  Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonOrange.prefab
  Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonPurple.prefab
  Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonRed.prefab
  Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonWhite.prefab
  Assets/Content/Items/Functional/Generic/BooksPapersPens/Crayons/CrayonYellow.prefab
  Assets/Content/Items/Functional/Parts/Power Cells/BluespacePowerCell.prefab
  Assets/Content/Items/Functional/Parts/Power Cells/HighPowerCell.prefab
  Assets/Content/Items/Functional/Parts/Power Cells/HyperPowerCell.prefab
  Assets/Content/Items/Functional/Parts/Power Cells/PowerCell.prefab
  Assets/Content/Items/Functional/Parts/Power Cells/SuperPowerCell.prefab
  Assets/Engine/Inventory/Item.cs
Labels: Type: Fix

#743 Fixed rendering bug when examining certain items
  Assets/Engine/Examine/CompositeItemSelector.cs
Labels: Type: Fix

#741 Fixes Seat Colliders and Examine Names
  Assets/Content/Furniture/Generic/Seats/Chairs/OfficeChair.prefab
  Assets/Content/Furniture/Generic/Seats/Chairs/OfficeChairGrey.prefab
  Assets/Content/Furniture/Generic/Seats/Chairs/PlasticChair.prefab
  Assets/Content/Furniture/Generic/Seats/Chairs/PlasticChairBlue.prefab
  Assets/Content/Furniture/Generic/Seats/Stools/BarStool.prefab
  Assets/Content/Furniture/Generic/Seats/Stools/Stool.prefab
Labels: Needs: Review/Testing, Priority: 1 - Average, Type: Fix
