Repository RE-SS3D/SS3D, pull requests merged in 2023-12, with the labels that each got.

#1370 fix tilemap menu
  Assets/Content/Systems/UI/Systems/Construction/ConstructionMenu.prefab
Labels: Tilemaps

#1381 Hologram flickering
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/ConstructionHologram.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/ConstructionHologramManager.cs
Labels: Tilemaps

#1388 Examine hotfix
  Assets/Content/Scenes/Game.unity
Labels: Examine

#1334 Switch between maps at run time
  Assets/Content/Scenes/Game.unity
  Assets/Content/Systems/UI/Systems/Construction/ConstructionMenu.prefab
  Assets/Content/Systems/UI/Systems/Construction/MapNameSlot.prefab
  Assets/Content/Systems/UI/Systems/Construction/MapNameSlot.prefab.meta
  Assets/Content/Systems/UI/Systems/Tilemap.meta
  Assets/Content/WorldObjects/Structures/WallMounts/Posters/Horizontal/PosterHorizontal.prefab
  Assets/Scripts/SS3D/Data/Management/SaveSystem.cs
  Assets/Scripts/SS3D/Systems/Tile/PlacedObjects/PlacedTileObject.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/ControlsOffInputField.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/ControlsOffInputField.cs.meta
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/ITileMenuTab.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/ITileMenuTab.cs.meta
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/MapNameSlot.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/MapNameSlot.cs.meta
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapBuildTab.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapBuildTab.cs.meta
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapLoadTab.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapLoadTab.cs.meta
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapMenu.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapSaveAndLoad.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapSaveTab.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapSaveTab.cs.meta
  Assets/Scripts/SS3D/Systems/Tile/TileResourceLoader.cs
  Assets/Scripts/SS3D/Systems/Tile/TileSystem.cs
  Builds/Game/Data/Tilemaps/TestMap.json
  Builds/Game/Data/Tilemaps/ministation.json
  Builds/Game/Data/Tilemaps/plenumstation.json
Labels: Tilemaps

#1368 Reimport connectables
  Assets/Art/Models/Furniture/Generic/Seats/DinerBooth.fbx
  Assets/Art/Models/Furniture/Generic/Surfaces/Tables.fbx
  Assets/Art/Models/Furniture/Generic/Surfaces/Tables.fbx.meta
  Assets/Art/Models/Furniture/Machines/Atmospherics/Vent&Scrubber.fbx
  Assets/Art/Models/Furniture/Machines/Atmospherics/Vent&Scrubber.fbx.meta
  Assets/Art/Models/Furniture/Machines/Supply/DisposalMachines.fbx
  Assets/Art/Models/Structures/Doors/SS13Airlocks.fbx
  Assets/Art/Models/Structures/Doors/SS13Airlocks.fbx.meta
  Assets/Art/Models/Structures/Floors/Plenums.fbx
  Assets/Art/Models/Structures/Floors/Tiles/DirtRockSandFloors.fbx
  Assets/Art/Models/Structures/Floors/Tiles/DirtRockSandFloors.fbx.meta
  Assets/Art/Models/Structures/Floors/Tiles/DirtTile.fbx
  Assets/Art/Models/Structures/Floors/Tiles/FancyCarpet.fbx
  Assets/Art/Models/Structures/Floors/Tiles/FloorTile.fbx
  Assets/Art/Models/Structures/Floors/Tiles/GrassTile.fbx
  Assets/Art/Models/Structures/Pipes/AtmosphericPipes.fbx
  Assets/Art/Models/Structures/Pipes/DisposalPipes.fbx
  Assets/Art/Models/Structures/Pipes/PipeMachinery.fbx
  Assets/Art/Models/Structures/WallMounts/AirAlarm.fbx
  Assets/Art/Models/Structures/Walls/MetalWallPanels.fbx
  Assets/Art/Models/Structures/Walls/MetalWallPanels.fbx.meta
  Assets/Art/Models/Structures/Walls/SteelWalls.fbx
  Assets/Art/Models/Structures/Wires/Cables.fbx
  Assets/Art/Models/Structures/Wires/Wires.fbx
  Assets/Content/WorldObjects/Furniture/Generic/Seats/DinnerBooth.prefab
  Assets/Content/WorldObjects/Furniture/Generic/Surfaces/Tables/TablePoker.prefab
  Assets/Content/WorldObjects/Structures/Doors/AirlockPanel.prefab
  Assets/Content/WorldObjects/Structures/Doors/CivillianAirlockDouble.prefab
  Assets/Content/WorldObjects/Structures/Doors/SecurityAirlock.prefab
  Assets/Content/WorldObjects/Structures/Floors/Plenum.prefab
  Assets/Scripts/SS3D/Systems/Tile/Connections/AdjacencyTypes/AdvancedAdjacency.cs
  Assets/Scripts/SS3D/Systems/Tile/Connections/AdjacencyTypes/OffsetAdjacency.cs
  Assets/Scripts/SS3D/Systems/Tile/Connections/AdjacencyTypes/PipeAdjacency.cs
  Assets/Scripts/SS3D/Systems/Tile/Connections/AdjacencyTypes/SimpleAdjacency.cs
Labels: Docs, Tilemaps, 3D, Design

#1410 New maps
  Builds/Game/Data/Tilemaps/ministation.json
  Builds/Game/Data/Tilemaps/plenumstation.json
  Builds/Game/Data/Tilemaps/teststation.json
Labels: Fix
