Repository RE-SS3D/SS3D, pull requests merged in 2023-01, with the labels that each got.

#947 Rework application settings
  Assets/AddressableAssetsData/link.xml
  Assets/Content/Data/ApplicationSettings.asset
  Assets/Content/Data/ApplicationSettings.asset.meta
  Assets/Content/Data/DefaultPrefabObjects.asset
  Assets/Content/Data/DefaultPrefabObjects.asset.meta
  Assets/Content/FishNet.meta
  Assets/Content/FishNet/Runtime.meta
  Assets/Content/FishNet/Runtime/DefaultPrefabObjects.asset
  Assets/Content/FishNet/Runtime/DefaultPrefabObjects.asset.meta
  Assets/Content/FishNet/Runtime/SS3DSpawnablePrefabs.asset.meta
  Assets/FishNet.meta
  Assets/FishNet/Runtime.meta
  Assets/Scenes/Startup.unity
  Assets/Scripts/External/FishNet/CodeGenerating/cecil-0.11.4/Mono.Cecil.sln.meta
  Assets/Scripts/External/FishNet/Runtime/Transporting/Transports/Tugboat/LiteNetLib/LiteNetLib.csproj.meta
  Assets/Scripts/SS3D/Core/ApplicationMode.cs
  Assets/Scripts/SS3D/Core/ApplicationMode.cs.meta
  Assets/Scripts/SS3D/Core/ApplicationStateManager.cs
  Assets/Scripts/SS3D/Core/ApplicationStateSystem.cs
  Assets/Scripts/SS3D/Core/ApplicationStateSystem.cs.meta
  Assets/Scripts/SS3D/Core/Events/ApplicationStartedEvent.cs
  Assets/Scripts/SS3D/Core/Intro/IntroUIHelper.cs
  Assets/Scripts/SS3D/Core/SessionNetworkHelper.cs
  Assets/Scripts/SS3D/Core/SessionNetworkSystem.cs
  Assets/Scripts/SS3D/Core/SessionNetworkSystem.cs.meta
  Assets/Scripts/SS3D/Core/Settings.meta
  Assets/Scripts/SS3D/Core/Settings/ApplicationSettings.cs
  Assets/Scripts/SS3D/Core/Settings/ApplicationSettings.cs.meta
  Assets/Scripts/SS3D/Core/Settings/LocalPlayer.cs
  Assets/Scripts/SS3D/Core/Settings/LocalPlayer.cs.meta
  Assets/Scripts/SS3D/Core/Settings/NetworkType.cs
  Assets/Scripts/SS3D/Core/Settings/NetworkType.cs.meta
  Assets/Scripts/SS3D/Core/Utils/ApplicationModeView.cs
  Assets/Scripts/SS3D/Core/Utils/CommandLineArgs.cs
  Assets/Scripts/SS3D/Core/Utils/CommandLineArgsSystem.cs
  Assets/Scripts/SS3D/Core/Utils/CommandLineArgsSystem.cs.meta
  Assets/Scripts/SS3D/Networking/UnauthorizedPlayer.cs
  Assets/Scripts/SS3D/Systems/Interactions/RadialInteractionView.cs
  Assets/Scripts/SS3D/Systems/Permissions/DisableIfNotAdmin.cs
  Assets/Scripts/SS3D/Systems/Permissions/PermissionSystem.cs
  Assets/Scripts/SS3D/Utils/ListExtensions.cs
  Assets/Scripts/SS3D/Utils/ListExtensions.cs.meta
  Library/FishNet.Runtime.Editor.PrefabObjects.Generation.Settings.json
  ProjectSettings/ProjectSettings.asset
Labels: Feature

#956 Join application settings fields
  Assets/Scripts/External/FishNet/CodeGenerating/cecil-0.11.4/Mono.Cecil.sln.meta
  Assets/Scripts/External/FishNet/Runtime/Transporting/Transports/Tugboat/LiteNetLib/LiteNetLib.csproj.meta
  Assets/Scripts/SS3D/Core/Settings/ApplicationSettings.cs
  Assets/Scripts/SS3D/Core/Utils/CommandLineArgsSystem.cs
  Assets/Scripts/SS3D/Data/AssetDatabases/GenericAssetDatabaseInspectorEditor.cs
  Assets/Scripts/SS3D/Data/AssetDatabases/GenericAssetDatabaseInspectorEditor.cs.meta
Labels: Feature

#959 Fix duplicate event system
  Assets/Scripts/IngameDebugConsole/IngameDebugConsole.prefab
Labels: Fix

#958 Fix double start bug
  Assets/Content/UI/Lobby/Canvas/Lobby Canvas.prefab
  Assets/Scenes/Lobby.unity
  Assets/Scripts/SS3D/Core/Behaviours/Actor.cs.meta
  Assets/Scripts/SS3D/Core/Behaviours/NetworkActor.cs.meta
  Assets/Scripts/SS3D/Systems/Lobby/UI/ChangeRoundStateView.cs
  Assets/Scripts/SS3D/Systems/Lobby/UI/RoundStateView.cs
Labels: Fix

#957 Fixes missing permissions.txt file
  Assets/Scripts/SS3D/Core/SystemLocator.cs
  Assets/Scripts/SS3D/Systems/Lobby/UI/LobbyReadyView.cs
  Assets/Scripts/SS3D/Systems/Permissions/PermissionSystem.cs
  Assets/Scripts/SS3D/Systems/Rounds/RoundSystemBase.cs
Labels: Fix

#963 Fix ready button issue with non-admin clients
  Assets/Scenes/Lobby.unity
  Assets/Scripts/SS3D/Systems/Lobby/UI/ChangeRoundStateView.cs
  Assets/Scripts/SS3D/Systems/Lobby/UI/LobbyReadyView.cs
Labels: Fix

#978 Sexier ReadMe
  Documents/Images/RESPACESTATION3D.png
  Documents/Images/ss3d.png
  README.md
Labels: Docs

#977 Adds interactive Pockets UI and two containers on thighs for pockets
  Assets/Content/Entities/Human/Human_Temporary.prefab
  Assets/Content/UI/HumanoidInventory.prefab
  Assets/Content/UI/Pocket.prefab
  Assets/Content/UI/Pocket.prefab.meta
  Assets/Scripts/SS3D/Systems/Storage/Containers/ContainerDescriptor.cs
  Assets/Scripts/SS3D/Systems/Storage/Containers/ContainerType.cs
  Assets/Scripts/SS3D/Systems/Storage/Containers/ContainerType.cs.meta
  Assets/Scripts/SS3D/Systems/Storage/Containers/Editor/ContainerDescriptorEditor.cs
  Assets/Scripts/SS3D/Systems/Storage/Containers/Inventory.cs
  Assets/Scripts/SS3D/Systems/Storage/UI/InventoryUi.cs
  Assets/Scripts/SS3D/Systems/Storage/UI/PocketView.cs
  Assets/Scripts/SS3D/Systems/Storage/UI/PocketView.cs.meta
Labels: Feature, Containers

#983 Required Documents
  Documents/CODE_OF_CONDUCT.md
  Documents/CONTRIBUTING.md
  Documents/Images/crypto.png
  Documents/Images/subscribestar.png
  README.md
Labels: Docs
