Repository RE-SS3D/SS3D, pull requests merged in 2023-11, with the labels that each got.

#1296 Update game version for monthly build
  ProjectSettings/ProjectSettings.asset
Labels: General Management

#1305 Fix Colliders
  Assets/Content/WorldObjects/Entities/Silicon/EngineeringBorg/EngineeringBorg.prefab
  Assets/Content/WorldObjects/Furniture/Storage/Lockers/Locker.prefab
  Assets/Content/WorldObjects/Furniture/Storage/Lockers/LockerSecure.prefab
  Assets/Content/WorldObjects/Furniture/Storage/Lockers/SecurityLocker.prefab
Labels: 3D

#1311 Don't allow walls to be placed over wall mounts
  Assets/Scripts/SS3D/Systems/Tile/BuildChecker.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMap.cs
  Assets/Scripts/Tests/Edit Mode/TileMapTests.cs
Labels: Tilemaps

#1310 Correct allowed rotation for placed objects
  Assets/Content/WorldObjects/Furniture/Generic/Surfaces/Tables/TableFrameSteel.prefab
  Assets/Content/WorldObjects/Furniture/Generic/Surfaces/Tables/TableFrameWood.prefab
  Assets/Content/WorldObjects/Furniture/Generic/Surfaces/Tables/TableGlass.prefab
  Assets/Content/WorldObjects/Furniture/Generic/Surfaces/Tables/TablePoker.prefab
  Assets/Content/WorldObjects/Furniture/Generic/Surfaces/Tables/TableSteel.prefab
  Assets/Content/WorldObjects/Furniture/Generic/Surfaces/Tables/TableWood.prefab
  Assets/Content/WorldObjects/Structures/Doors/CivillianAirlock.prefab
  Assets/Content/WorldObjects/Structures/Doors/SecurityAirlock.prefab
  Assets/Content/WorldObjects/Structures/Floors/Catwalk.prefab
  Assets/Content/WorldObjects/Structures/Floors/Lattice.prefab
  Assets/Content/WorldObjects/Structures/Floors/Plenum.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Carpet/FancyCarpetRed.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Dirt/TileDirt1.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Dirt/TileDirt2.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Dirt/TileDirt3.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Dirt/TileDirt4.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Dirt/TileDirt5.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Dirt/TileDirt6.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Grass/TileGrass.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Reinforced/TileReinforced.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Steel/TileBar.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Steel/TileGrey.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Steel/TileGreyDark.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Steel/TileKitchen.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Steel/TileWhite.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/TilePlating.prefab
  Assets/Content/WorldObjects/Structures/Floors/Tiles/Wood/TileWood.prefab
  Assets/Content/WorldObjects/Structures/Pipes/Atmospherics/AtmosPipesL1.prefab
  Assets/Content/WorldObjects/Structures/Pipes/Atmospherics/AtmosPipesL2.prefab
  Assets/Content/WorldObjects/Structures/Pipes/Atmospherics/AtmosPipesL3.prefab
  Assets/Content/WorldObjects/Structures/Pipes/Atmospherics/AtmosPipesL4.prefab
  Assets/Content/WorldObjects/Structures/Walls/SteelGirder.prefab
  Assets/Content/WorldObjects/Structures/Walls/SteelWall.prefab
  Assets/Content/WorldObjects/Structures/Walls/SteelWallReinforced.prefab
  Assets/Content/WorldObjects/Structures/Walls/SteelWindow.prefab
  Assets/Content/WorldObjects/Structures/Walls/SteelWindowReinforced.prefab
  Assets/Content/WorldObjects/Structures/Wires/Cables.prefab
  Assets/Content/WorldObjects/Structures/Wires/WiresBlue.prefab
  Assets/Content/WorldObjects/Structures/Wires/WiresBrown.prefab
  Assets/Content/WorldObjects/Structures/Wires/WiresGreen.prefab
  Assets/Content/WorldObjects/Structures/Wires/WiresOrange.prefab
  Assets/Content/WorldObjects/Structures/Wires/WiresPink.prefab
  Assets/Content/WorldObjects/Structures/Wires/WiresPurple.prefab
  Assets/Content/WorldObjects/Structures/Wires/WiresRed.prefab
  Assets/Content/WorldObjects/Structures/Wires/WiresTeal.prefab
  Assets/Content/WorldObjects/Structures/Wires/WiresWhite.prefab
  Assets/Content/WorldObjects/Structures/Wires/WiresYellow.prefab
  Assets/Scripts/SS3D/Systems/Tile/TileMap.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/CustomGhostTileObjectRotation.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/CustomGhostTileObjectRotation.cs.meta
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/GhostManager.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/ICustomGhostRotation.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/ICustomGhostRotation.cs.meta
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapCreator.cs
Labels: Tilemaps

#1317 Clear only object in given direction
  Assets/Scripts/SS3D/Systems/Tile/TileMap.cs
Labels: Tilemaps, Fix

#1318 Fix UI disappearing on host death
  Assets/Scripts/SS3D/Systems/Inventory/Containers/HumanInventory.cs
Labels: UI/UX, Fix

#1303 Directionnal adjacencies
  Assets/Art/Models/Furniture/Generic/Seats/DinerBooth.fbx
  Assets/Art/Models/Furniture/Generic/Seats/DinerBooth.fbx.meta
  Assets/Content/Data/TileMap/Resources/Furniture/Generic/Seats/DinnerBooth.asset
  Assets/Content/Data/TileMap/Resources/Furniture/Generic/Seats/DinnerBooth.asset.meta
  Assets/Content/Scenes/Game.unity
  Assets/Content/WorldObjects/Furniture/Generic/Seats/DinnerBooth.prefab
  Assets/Content/WorldObjects/Furniture/Generic/Seats/DinnerBooth.prefab.meta
  Assets/Scripts/SS3D/Systems/Tile/Connections/AdjacencyShape.cs
  Assets/Scripts/SS3D/Systems/Tile/Connections/AdjacencyTypes/DirectionnalShapeResolver.cs
  Assets/Scripts/SS3D/Systems/Tile/Connections/AdjacencyTypes/DirectionnalShapeResolver.cs.meta
  Assets/Scripts/SS3D/Systems/Tile/Connections/DirectionalAdjacencyConnector.cs
  Assets/Scripts/SS3D/Systems/Tile/Connections/DirectionalAdjacencyConnector.cs.meta
  Assets/Scripts/SS3D/Systems/Tile/PlacedObjects/PlacedTileObject.cs
  Assets/Scripts/SS3D/Systems/Tile/SO/TileObjectSo.cs
  Assets/Scripts/SS3D/Systems/Tile/TileHelper.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMap.cs
  Assets/Scripts/SS3D/Utils/ListExtensions.cs
Labels: Tilemaps

#1326 Fix Table type connection bias
  Assets/Content/Data/TileMap/Resources/Furniture/Generic/Surfaces/Tables/TableGlass.asset
  Assets/Content/Data/TileMap/Resources/Furniture/Generic/Surfaces/Tables/TableSteel.asset
Labels: Fix

#1321 Bigger Map
  Assets/Content/Data/TileMap/Resources/Entities/EngiBorg.asset
  Assets/Content/Data/TileMap/Resources/Entities/EngiBorg.asset.meta
  Assets/Content/WorldObjects/Structures/Doors/SecurityAirlock.prefab
  Builds/Game/Data/Tilemaps/TestMap.json
  Builds/Game/Data/Tilemaps/UnnamedMap.json
Labels: Map

#1344 Fast construction
  Assets/Content/Systems/Input/Controls.inputactions
  Assets/Content/Systems/UI/Lobby/Canvas/PlayerCanvas.prefab
  Assets/Content/Systems/UI/Systems/Construction/ConstructionMenu.prefab
  Assets/Content/Systems/UI/Systems/Construction/ConstructionSlot.prefab
  Assets/Scripts/SS3D/Systems/Inputs/Controls.cs
  Assets/Scripts/SS3D/Systems/Substances/SubstanceContainer.cs
  Assets/Scripts/SS3D/Systems/Tile/TileHelper.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/AssetGridManager.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/AssetGridManager.cs.meta
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/BuildGhost.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/BuildGhost.cs.meta
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/CustomGhostTileObjectRotation.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/GhostManager.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/ICustomGhostRotation.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapCreator.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapCreatorTab.cs
  Assets/Scripts/SS3D/Utils/MathUtility.cs
Labels: Tilemaps

#1359 Reimport wallmounts
  Assets/Art/Models/Structures/WallMounts/APC.fbx
  Assets/Art/Models/Structures/WallMounts/AirAlarm.fbx
  Assets/Art/Models/Structures/WallMounts/FireAlarm.fbx
  Assets/Art/Models/Structures/WallMounts/LightSwitch.fbx
  Assets/Art/Models/Structures/WallMounts/Lights.fbx
  Assets/Art/Models/Structures/WallMounts/Mirror.fbx
  Assets/Art/Models/Structures/WallMounts/Posters.fbx
  Assets/Art/Models/Structures/WallMounts/Posters.fbx.meta
  Assets/Art/Models/Structures/WallMounts/WallPanels/MetalWallPanels.fbx
  Assets/Art/Models/Structures/WallMounts/WallPanels/MetalWallPanels.fbx.meta
  Assets/Art/Models/Structures/WallMounts/WallPanels/WoodWallPanels.fbx
  Assets/Art/Models/Structures/WallMounts/WallPanels/WoodWallPanels.fbx.meta
  Assets/Content/Data/TileMap/Resources/Structures/WallMounts/Mirror.asset
  Assets/Content/Data/TileMap/Resources/Structures/WallMounts/Mirror.asset.meta
  Assets/Content/WorldObjects/Structures/WallMounts/Mirror.prefab
  Assets/Content/WorldObjects/Structures/WallMounts/Mirror.prefab.meta
  Builds/Game/Config/permissions.txt
  Builds/Game/Data/Tilemaps/TestMap.json
Labels: 3D, Fix
