Repository RE-SS3D/SS3D, pull requests merged in 2023-03, with the labels that each got.

#1051 Asset Data cleanup
  Assets/AddressableAssetsData/AssetGroups/InteractionIcons.asset
  Assets/Art/UI/Interactions/Discard.asset
  Assets/Art/UI/Interactions/Discard.asset.meta
  Assets/Art/UI/Interactions/Honk.asset
  Assets/Art/UI/Interactions/Honk.asset.meta
  Assets/Art/UI/Interactions/Nuke.asset
  Assets/Art/UI/Interactions/Nuke.asset.meta
  Assets/Art/UI/Interactions/Open.asset
  Assets/Art/UI/Interactions/Open.asset.meta
  Assets/Art/UI/Interactions/Power.asset
  Assets/Art/UI/Interactions/Power.asset.meta
  Assets/Art/UI/Interactions/Take.asset
  Assets/Art/UI/Interactions/Take.asset.meta
  Assets/Content/Data/DefaultPrefabObjects.asset
  Assets/Content/Data/Icons/InteractionIcons.asset
  Assets/Content/WorldObjects/Entities/Silicon/EngineeringBorg/EngineeringBorg.prefab
  Assets/Scripts/EditorTests/AssetDataTests.cs
  Assets/Scripts/SS3D/CodeGeneration/EnumCreator.cs
  Assets/Scripts/SS3D/Data/AssetDatabases/AssetDatabase.cs
  Assets/Scripts/SS3D/Data/AssetDatabases/AssetDatabaseSettings.cs
  Assets/Scripts/SS3D/Data/AssetDatabases/InspectorEditor/AssetDatabaseInspectorEditor.cs
  Assets/Scripts/SS3D/Data/AssetDatabases/InspectorEditor/AssetDatabaseSettingsInspectorEditor.cs
  Assets/Scripts/SS3D/Data/Assets.cs
  Assets/Scripts/SS3D/Data/Enums/AssetDatabases.cs
  Assets/Scripts/SS3D/Data/Enums/AssetDatabases.cs.meta
  Assets/Scripts/SS3D/Data/Enums/InteractionIcons.cs
  Assets/Scripts/SS3D/Systems/Furniture/Nuke.cs
  Assets/Scripts/SS3D/Systems/Inventory/Items/ItemSystem.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapCreator.cs
Labels: Feature

#1063 Fix issue on built clients not being able to join server on the editor
  Assets/Scripts/SS3D/Core/SessionNetworkSystem.cs
  Assets/Scripts/SS3D/Core/Settings/ApplicationSettings.cs
  Assets/Scripts/SS3D/Core/Utils/CommandLineArgs.cs
  Assets/Scripts/SS3D/Core/Utils/CommandLineArgsSystem.cs
  Assets/Settings/ApplicationSettings.asset
  Builds/Start SS3D Client - GhostOfBeep.bat
  Builds/Start SS3D Client - John.bat
  Builds/Start SS3D Host.bat
Labels: Networking, Bug: Confirmed

#1071 Update Unity version and fix errors
  Assets/Scripts/SS3D/Core/ApplicationStateSystem.cs
  Assets/Scripts/SS3D/Interactions/ClientDelayedInteraction.cs
  Assets/Scripts/SS3D/Interactions/LoadingBar.cs
  Assets/Scripts/SS3D/Interactions/UI/InteractionMenuView.cs
  Assets/Scripts/SS3D/Systems/Entities/EntitySystem.cs
  Assets/Scripts/SS3D/Systems/Gamemodes/Modes/Gamemode.cs
  Assets/Scripts/SS3D/Systems/Gamemodes/UI/GamemodeObjectivePanelView.cs
  Assets/Scripts/SS3D/Systems/Health/HealthController.cs
  Assets/Scripts/SS3D/Systems/Input/Controls.cs
  Assets/Scripts/SS3D/Systems/Inventory/UI/ContainerUi.cs
  Assets/Scripts/SS3D/Systems/Inventory/UI/InventoryView.cs
  Assets/Scripts/SS3D/Systems/Inventory/UI/ItemGrid.cs
  Assets/Scripts/SS3D/Systems/Inventory/UI/ItemGridItem.cs
  Assets/Scripts/SS3D/Systems/Lobby/UI/PlayerUsernameListView.cs
  Assets/Scripts/SS3D/Systems/Permissions/DisableIfNotAdmin.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/GhostManager.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapCreator.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/PackageManagerSettings.asset
  ProjectSettings/Packages/com.coimbrastudios.core/LintingSettings.asset
  ProjectSettings/ProjectVersion.txt
Labels: General Management

#1072 Outdated branch: update unity version
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
Labels: General Management

#1082 Fix camera rotation
  Assets/Scripts/SS3D/Systems/Screens/CameraFollow.cs
Labels: Fix

#1084 Move addressables folder
  Assets/Content/Addressables.meta
  Assets/Content/Addressables/AddressableAssetSettings.asset
  Assets/Content/Addressables/AddressableAssetSettings.asset.meta
  Assets/Content/Addressables/AssetGroupTemplates.meta
  Assets/Content/Addressables/AssetGroupTemplates/Packed Assets.asset
  Assets/Content/Addressables/AssetGroupTemplates/Packed Assets.asset.meta
  Assets/Content/Addressables/AssetGroups.meta
  Assets/Content/Addressables/AssetGroups/Built In Data.asset
  Assets/Content/Addressables/AssetGroups/Built In Data.asset.meta
  Assets/Content/Addressables/AssetGroups/Default Local Group.asset
  Assets/Content/Addressables/AssetGroups/Default Local Group.asset.meta
  Assets/Content/Addressables/AssetGroups/InteractionIcons.asset
  Assets/Content/Addressables/AssetGroups/InteractionIcons.asset.meta
  Assets/Content/Addressables/AssetGroups/Items.asset
  Assets/Content/Addressables/AssetGroups/Items.asset.meta
  Assets/Content/Addressables/AssetGroups/Schemas.meta
  Assets/Content/Addressables/AssetGroups/Schemas/Built In Data_PlayerDataGroupSchema.asset
  Assets/Content/Addressables/AssetGroups/Schemas/Built In Data_PlayerDataGroupSchema.asset.meta
  Assets/Content/Addressables/AssetGroups/Schemas/Default Local Group_BundledAssetGroupSchema.asset
  Assets/Content/Addressables/AssetGroups/Schemas/Default Local Group_BundledAssetGroupSchema.asset.meta
  Assets/Content/Addressables/AssetGroups/Schemas/Default Local Group_ContentUpdateGroupSchema.asset
  Assets/Content/Addressables/AssetGroups/Schemas/Default Local Group_ContentUpdateGroupSchema.asset.meta
  Assets/Content/Addressables/AssetGroups/Schemas/InteractionIcons_BundledAssetGroupSchema.asset
  Assets/Content/Addressables/AssetGroups/Schemas/InteractionIcons_BundledAssetGroupSchema.asset.meta
  Assets/Content/Addressables/AssetGroups/Schemas/InteractionIcons_ContentUpdateGroupSchema.asset
  Assets/Content/Addressables/AssetGroups/Schemas/InteractionIcons_ContentUpdateGroupSchema.asset.meta
  Assets/Content/Addressables/AssetGroups/Schemas/Items_BundledAssetGroupSchema.asset
  Assets/Content/Addressables/AssetGroups/Schemas/Items_BundledAssetGroupSchema.asset.meta
  Assets/Content/Addressables/AssetGroups/Schemas/Items_ContentUpdateGroupSchema.asset
  Assets/Content/Addressables/AssetGroups/Schemas/Items_ContentUpdateGroupSchema.asset.meta
  Assets/Content/Addressables/DataBuilders.meta
  Assets/Content/Addressables/DataBuilders/BuildScriptFastMode.asset
  Assets/Content/Addressables/DataBuilders/BuildScriptFastMode.asset.meta
  Assets/Content/Addressables/DataBuilders/BuildScriptPackedMode.asset
  Assets/Content/Addressables/DataBuilders/BuildScriptPackedMode.asset.meta
  Assets/Content/Addressables/DataBuilders/BuildScriptPackedPlayMode.asset
  Assets/Content/Addressables/DataBuilders/BuildScriptPackedPlayMode.asset.meta
  Assets/Content/Addressables/DataBuilders/BuildScriptVirtualMode.asset
  Assets/Content/Addressables/DataBuilders/BuildScriptVirtualMode.asset.meta
  Assets/Content/Addressables/DefaultObject.asset
  Assets/Content/Addressables/DefaultObject.asset.meta
  Assets/Content/Addressables/ProfileDataSourceSettings.asset
  Assets/Content/Addressables/ProfileDataSourceSettings.asset.meta
  Assets/Content/Addressables/Windows.meta
  Assets/Content/Addressables/Windows/addressables_content_state.bin
  Assets/Content/Addressables/Windows/addressables_content_state.bin.meta
  UnityEngine.Content.Addressables.BuildPath/StandaloneWindows64/ae01572a78438f97c64efd247b2c4519_unitybuiltinshaders_a4b6a35f52f878396914216b715751fc.bundle
  UnityEngine.Content.Addressables.BuildPath/StandaloneWindows64/interactionicons_assets_all_18fe10167606bbe21bb5d6db0810f88c.bundle
  UnityEngine.Content.Addressables.BuildPath/StandaloneWindows64/items_assets_all_d8a5d5c9b4bd8c47ba3504ec72d6693c.bundle
Labels: General Management

#1118 fix port server still busy
  Assets/Scripts/SS3D/Core/SessionNetworkSystem.cs
Labels: Fix

#1115 hotfix #1030
  Assets/Scripts/SS3D/Systems/Inventory/Containers/Container.cs
  Assets/Scripts/SS3D/Systems/Inventory/Containers/Inventory.cs
  Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs
Labels: Fix

#1113 Cleanup /Content/UI/
  Assets/Content/UI/Lobby/IntroCanvas.prefab
  Assets/Content/UI/Lobby/IntroCanvas.prefab.meta
  Assets/Content/UI/Lobby/ServerConnectionScreenCanvas.prefab
  Assets/Content/UI/Lobby/ServerConnectionScreenCanvas.prefab.meta
  Assets/Content/UI/Systems/Containers.meta
  Assets/Content/UI/Systems/Containers/ContainerDisplay.prefab
  Assets/Content/UI/Systems/Containers/ContainerDisplay.prefab.meta
  Assets/Content/UI/Systems/Containers/Inventory.meta
  Assets/Content/UI/Systems/Containers/Inventory/GenericPanel.prefab
  Assets/Content/UI/Systems/Containers/Inventory/GenericPanel.prefab.meta
  Assets/Content/UI/Systems/Containers/Inventory/HumanoidInventory.prefab
  Assets/Content/UI/Systems/Containers/Inventory/HumanoidInventory.prefab.meta
  Assets/Content/UI/Systems/Containers/Inventory/Identification.prefab
  Assets/Content/UI/Systems/Containers/Inventory/Identification.prefab.meta
  Assets/Content/UI/Systems/Containers/Inventory/ItemDisplay.prefab
  Assets/Content/UI/Systems/Containers/Inventory/ItemDisplay.prefab.meta
  Assets/Content/UI/Systems/Containers/Inventory/ItemGridItem.prefab
  Assets/Content/UI/Systems/Containers/Inventory/ItemGridItem.prefab.meta
  Assets/Content/UI/Systems/Containers/Inventory/ItemGridSlot.prefab
  Assets/Content/UI/Systems/Containers/Inventory/ItemGridSlot.prefab.meta
  Assets/Content/UI/Systems/Containers/Inventory/LeftHand.prefab
  Assets/Content/UI/Systems/Containers/Inventory/LeftHand.prefab.meta
  Assets/Content/UI/Systems/Containers/Inventory/Pocket.prefab
  Assets/Content/UI/Systems/Containers/Inventory/Pocket.prefab.meta
  Assets/Content/UI/Systems/Containers/Inventory/RightHand.prefab
  Assets/Content/UI/Systems/Containers/Inventory/RightHand.prefab.meta
Labels: General Management

#1126 Reworks Actor and updates references
  Assets/Scripts/SS3D/Core/Behaviours/Actor.cs
  Assets/Scripts/SS3D/Core/Behaviours/IActor.cs
  Assets/Scripts/SS3D/Core/Behaviours/IActor.cs.meta
  Assets/Scripts/SS3D/Core/Behaviours/NetworkActor.cs
  Assets/Scripts/SS3D/Interactions/InteractionSource.cs
  Assets/Scripts/SS3D/Interactions/InteractionTargetBehaviour.cs
  Assets/Scripts/SS3D/Interactions/InteractionTargetNetworkBehaviour.cs
  Assets/Scripts/SS3D/Interactions/LoadingBar.cs
  Assets/Scripts/SS3D/Interactions/SS3D.Interactions.asmdef
  Assets/Scripts/SS3D/Interactions/UI/InteractionMenuView.cs
  Assets/Scripts/SS3D/Networking/NetworkPhysicsDebug.cs
  Assets/Scripts/SS3D/Networking/SS3D.Networking.asmdef
  Assets/Scripts/SS3D/Rendering/EmissiveMaterialController.cs
  Assets/Scripts/SS3D/Rendering/SS3D.Rendering.asmdef
  Assets/Scripts/SS3D/Systems/Entities/Entity.cs
  Assets/Scripts/SS3D/Systems/Entities/EntitySystem.cs
  Assets/Scripts/SS3D/Systems/Entities/Humanoid/HumanoidController.cs
  Assets/Scripts/SS3D/Systems/Entities/MindSystem.cs
  Assets/Scripts/SS3D/Systems/Entities/Silicon/ThreadController.cs
  Assets/Scripts/SS3D/Systems/Gamemodes/UI/GamemodeObjectivePanelView.cs
  Assets/Scripts/SS3D/Systems/Health/StaminaBarView.cs
  Assets/Scripts/SS3D/Systems/Health/StaminaController.cs
  Assets/Scripts/SS3D/Systems/IngameConsoleSystem/ConsolePanelView.cs
  Assets/Scripts/SS3D/Systems/Interactions/RadialInteractionButton.cs
  Assets/Scripts/SS3D/Systems/Interactions/RadialInteractionView.cs
  Assets/Scripts/SS3D/Systems/Inventory/Containers/Inventory.cs
  Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs
  Assets/Scripts/SS3D/Systems/SS3D.Systems.asmdef
  Assets/Scripts/SS3D/Systems/Screens/CameraFollow.cs
  Assets/Scripts/SS3D/Systems/Screens/GameScreen.cs
  Assets/Scripts/SS3D/Systems/Screens/PlayerCameraSystem.cs
Labels: Docs, General Management

#1122 InputSystem fixes and features
  Assets/Content/Input/Controls.inputactions
  Assets/Content/Input/Controls.inputactions.meta
  Assets/InputSystem.inputsettings.asset
  Assets/InputSystem.inputsettings.asset.meta
  Assets/Scenes/Lobby.unity
  Assets/Scenes/Startup.unity
  Assets/Scripts/SS3D/Networking/NetworkPhysicsDebug.cs
  Assets/Scripts/SS3D/Systems/Entities/Debug/MindSwapDebug.cs
  Assets/Scripts/SS3D/Systems/Entities/Humanoid/HumanoidController.cs
  Assets/Scripts/SS3D/Systems/Entities/Humanoid/HumanoidGhostController.cs
  Assets/Scripts/SS3D/Systems/Entities/Humanoid/HumanoidLivingController.cs
  Assets/Scripts/SS3D/Systems/Entities/Silicon/ThreadController.cs
  Assets/Scripts/SS3D/Systems/Gamemodes/UI/GamemodeObjectivePanelView.cs
  Assets/Scripts/SS3D/Systems/IngameConsoleSystem/ConsolePanelView.cs
  Assets/Scripts/SS3D/Systems/Input/Controls.cs
  Assets/Scripts/SS3D/Systems/Input/InputSystem.cs
  Assets/Scripts/SS3D/Systems/Inputs.meta
  Assets/Scripts/SS3D/Systems/Inputs/Controls.cs
  Assets/Scripts/SS3D/Systems/Inputs/Controls.cs.meta
  Assets/Scripts/SS3D/Systems/Inputs/InputSystem.cs
  Assets/Scripts/SS3D/Systems/Inputs/InputSystem.cs.meta
  Assets/Scripts/SS3D/Systems/Interactions/InteractionController.cs
  Assets/Scripts/SS3D/Systems/Interactions/RadialInteractionView.cs
  Assets/Scripts/SS3D/Systems/Inventory/Containers/Hands.cs
  Assets/Scripts/SS3D/Systems/Inventory/UI/ToggleInternalClothingUI.cs
  Assets/Scripts/SS3D/Systems/Screens/CameraFollow.cs
  Assets/Scripts/SS3D/Systems/Screens/GameScreensController.cs
  Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapCreator.cs
Labels: Feature, Fix

#1095 Clean project root
  Data
  Mirror.Tests.csproj.DotSettings
  UnityEngine.Content.Addressables.BuildPath/StandaloneWindows64/ae01572a78438f97c64efd247b2c4519_unitybuiltinshaders_a4b6a35f52f878396914216b715751fc.bundle
  UnityEngine.Content.Addressables.BuildPath/StandaloneWindows64/interactionicons_assets_all_18fe10167606bbe21bb5d6db0810f88c.bundle
  UnityEngine.Content.Addressables.BuildPath/StandaloneWindows64/items_assets_all_d8a5d5c9b4bd8c47ba3504ec72d6693c.bundle
Labels: General Management

#1117 change containerViewedCondition to fix issue 1116
  Assets/Content/Data/ObserverConditions/ContainerViewedCondition.cs
  Assets/Content/WorldObjects/Items/Functional/Storage/Objects/ToolBoxes/ToolboxBlue.prefab
Labels: Fix
