Repository RE-SS3D/SS3D, pull requests merged in 2024-01, with the labels that each got.

#1411 Update game version
  ProjectSettings/ProjectSettings.asset
Labels: General Management

#1413 Improve Circuit algorithms
  Assets/Content/WorldObjects/Furniture/Machines/Engineering/SMES.prefab
  Assets/Scripts/SS3D/Systems/Electricity/BasicBattery.cs
  Assets/Scripts/SS3D/Systems/Electricity/Circuit.cs
  Assets/Scripts/SS3D/Systems/Electricity/Circuit.cs.meta
  Assets/Scripts/Tests/Edit Mode/ElectricityTests/CircuitTests.cs
Labels: Electricity

#1412 Activate ragdoll after death
  Assets/Scripts/SS3D/Systems/Entities/Human.cs
  Assets/Scripts/SS3D/Systems/Entities/Humanoid/Ragdoll.cs
  Assets/Scripts/SS3D/Systems/Health/BodyParts/Bodypart.cs
  Assets/Scripts/SS3D/Systems/Health/BodyParts/HeadBodyPart.cs
  Assets/Scripts/SS3D/Systems/Health/BodyParts/HumanTorso.cs
Labels: Movement
